export { default as Badge } from "./Badge";
export { default as Snackbar } from "./Snackbar";
export type { SnackbarProps, SnackbarVariant } from "./Snackbar";
export { default as Spinner } from "./Spinner";
export { default as BentoGrid } from "./BentoGrid";
export { default as FeaturedProject } from "./FeaturedProject";
export { default as MagneticButton } from "./MagneticButton";
export { default as ProjectCard } from "./ProjectCard";
export type { ProjectTile } from "./ProjectCard";
export { BUTTON_VARIANTS } from "@/styles/button.style";
export type { ButtonVariant } from "@/styles/button.style";
